name: CMake (macOS)

on: [push, pull_request]

env:
  BUILD_TYPE: RelWithDebInfo
  BUILD_NUMBER: ${{github.run_number}}
  OPENSSL_ROOT_DIR: /usr/local/opt/openssl@1.1
  Qt5_DIR: /usr/local/opt/qt5
  QT_QPA_PLATFORM: offscreen
  MACOSX_DEPLOYMENT_TARGET: 10.15

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install libraries
        run: brew install web-eid/gtest/gtest qt@5

      - name: Create build directory
        run: mkdir build

      - name: Configure CMake
        working-directory: ${{github.workspace}}/build
        run: cmake ..

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: |
          cmake --build .

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: demo-libelectronic-id-macos-build-${{github.run_number}}
          path: |
            build/*/*/*.pkg
            build/*/*/*.dmg
